# Generated by Django 4.1.6 on 2023-02-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pennapps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="firstName",
            field=models.CharField(
                default="first", max_length=30, verbose_name="First_name"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="lastName",
            field=models.CharField(
                default="last", max_length=30, verbose_name="Last_name"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="birthday",
            field=models.CharField(default="", max_length=20, verbose_name="Birthday"),
        ),
        migrations.AddField(
            model_name="application",
            name="first_hackathon",
            field=models.CharField(
                default="", max_length=30, verbose_name="First_hackathon"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="major",
            field=models.CharField(default="", max_length=50, verbose_name="Major"),
        ),
        migrations.AddField(
            model_name="application",
            name="phone_number",
            field=models.CharField(
                default="", max_length=20, verbose_name="Phone_number"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="q1",
            field=models.TextField(default="", verbose_name="Q1_answer"),
        ),
        migrations.AddField(
            model_name="application",
            name="q2",
            field=models.TextField(default="", verbose_name="Q2_answer"),
        ),
        migrations.AddField(
            model_name="application",
            name="school",
            field=models.CharField(default="", max_length=50, verbose_name="School"),
        ),
        migrations.AddField(
            model_name="application",
            name="team_member_1",
            field=models.EmailField(
                default="", max_length=254, verbose_name="Team_member_1"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="team_member_2",
            field=models.EmailField(
                default="", max_length=254, verbose_name="Team_member_2"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="team_member_3",
            field=models.EmailField(
                default="", max_length=254, verbose_name="Team_member_3"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="year",
            field=models.CharField(default="", max_length=30, verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="application",
            name="applicant",
            field=models.CharField(default="", max_length=50, verbose_name="Applicant"),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACPT", "Accepted"),
                    ("RJCT", "Rejected"),
                    ("WLST", "Waitlisted"),
                    ("PROC", "Processing"),
                ],
                default="PROC",
                max_length=4,
            ),
        ),
    ]
