# Generated by Django 4.1.6 on 2023-02-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pennapps", "0002_applicant_firstname_applicant_lastname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="applicant",
        ),
    ]
