# Generated by Django 4.1.6 on 2023-02-05 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pennapps", "0003_remove_application_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="applicant",
            field=models.OneToOneField(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
